---
# adapted from https://www.fullstaq.com/knowledge-hub/blogs/setting-up-your-own-k3s-home-cluster
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
