# https://github.com/techno-tim/launchpad/blob/master/kubernetes/traefik-cert-manager/cert-manager/issuers/letsencrypt-staging.yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your@email.com  # cloudflare email. SHOULD BE A VAULT SECRET
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: your@email.com  # cloudflare email. SHOULD BE A VAULT SECRET
            apiTokenSecretRef:
              name: cloudflare-token-secret  # from cloudflare
              key: cloudflare-token
        selector:
          dnsZones:
            - "your.zone.com"  # cloudflare zone
