apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: metallb
    component: speaker
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
      - args:
        - --port=7472
        - --log-level=warn  # default info. : `all`, `debug`, `info`, `warn`, `error` or `none`
        name: speaker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metallb
    component: controller
  name: controller
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
      - args:
        - --port=7472
        - --log-level=warn  # default info. : `all`, `debug`, `info`, `warn`, `error` or `none`
        name: controller
