---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
#  - secret-private-gh-infra-repository-sealed.yaml
#  - secret-private-gh-credentials-sealed.yaml

patches:
  - path: patch-appproj-dev1-sourceRepos.yaml
  - path: patch-appset-infrastructure-generators.yaml
  - path: patch-appset-infrastructure-source.yaml
  - path: patch-appset-tenants-generators.yaml
  - path: patch-appset-tenants-source.yaml