---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-appset
  namespace: argocd
spec:
  generators:
    - git:  
        repoURL: https://github.com/USERNAME/YOUR-PRIVATE-FORK-OF-THIS-REPO.git
        revision: main
        files:
          - path: "tenants/**/config.json"
