---
# k3s-io/k3s-ansible, proxy from Techno-Tim

- name: Wait for control-plane at apiserver_endpoint
  ansible.builtin.wait_for:
    host: "{{ apiserver_endpoint }}"
    port: "6443"
    timeout: 120

- name: Deploy K3s http_proxy conf
  ansible.builtin.include_tasks: http_proxy.yml
  when: proxy_env is defined

- name: Copy K3s service file
  ansible.builtin.template:
    src: k3s-agent.service.j2
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: "0755"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-agent
    daemon_reload: true
    state: started
    enabled: true
