# last checked for traefik helm chart v27.0.2

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=true"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"  # normally info

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external  # can be named anything. External as in external to cluster.
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  labels: {}
  spec:
    loadBalancerIP: 192.168.your.ip.here  # this should be an IP in the MetalLB range
    externalTrafficPolicy: Local  # default Cluster
    # traffic policy Local forces MetalLB speaker to announce the IP for this service from the cluster node hosting the traefik pod/service.
    # it isn't clear that it is mandatory for anything
    # might mean replicas must be 2, to have traefik on each node, when workloads start getting deployed to different nodes
  loadBalancerSourceRanges: []
  externalIPs: []

# This example topologySpreadConstraints forces the scheduler to put traefik pods
# on nodes where no other traefik pods are scheduled.
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: '{{ template "traefik.name" . }}'
