---
# copied 23.12.2023 from https://www.fullstaq.com/knowledge-hub/blogs/setting-up-your-own-k3s-home-cluster

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-home-selfsigned
  namespace: test-ingress
spec:
  commonName: "traefik.your.domain.com"
  secretName: cluster-home-selfsigned-tls
  dnsNames:
    - "traefik.your.domain.com"
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
