---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- ns-longhorn.yaml
- ingressRoute-dashboard.yaml
- mware-longhorn-headers.yaml

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.6.1
  releaseName: longhorn
  namespace: longhorn-system
  valuesFile: values-longhorn.yaml
