---
# see argocd-repo-server overlay example: https://github.com/argoproj/argo-cd/blob/master/manifests/ha/base/overlays/argocd-repo-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /tmp/argo-gitops.git
              name: local-git-repo
              readOnly: true
      volumes:
        - name: local-git-repo
          hostPath:
            path: /tmp/argo-gitops.git
            type: Directory
