---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-appset
  namespace: argocd
spec:
  generators:
    - git:  
        repoURL: file:///tmp/argo-gitops.git
        revision: main
        files:
          - path: "tenants/**/config.json" 
