---
apiVersion: v1
kind: Service
metadata:
  name: test-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.2
spec:
  type: LoadBalancer
  selector:
    app: test-lb
  ports:
  - name: http
    port: 80
