---
# adapted from techno-tim.
- name: Create KubeVIP templates on Ansible Controller.
  run_once: true
  when: ansible_hostname == groups['server'][0] or groups['server'][0] in ansible_facts['all_ipv4_addresses']
  block:
    # https://stackoverflow.com/a/26399105
    # https://devops.stackexchange.com/a/3772
    - name: Download vip rbac manifest to gitops repo on ansible controller
      ansible.builtin.get_url:
        url: "https://kube-vip.io/manifests/rbac.yaml"
        dest: "{{ lookup('env', 'PWD') }}/infrastructure/kubevip/base/rbac-vip.yaml"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      delegate_to: localhost
    - name: Copy VIP manifest template to gitops repo on ansible controller
      ansible.builtin.template:
        src: "vip-ds.yaml.j2"
        dest: "{{ lookup('env', 'PWD') }}/infrastructure/kubevip/base/ds-vip.yaml"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      delegate_to: localhost
