---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: 2.15.3
  releaseName: sealed-secrets
  namespace: kube-system
  includeCRDs: true
  valuesFile: values-sealed-secrets.yaml