# last checked for sealed-secrets helm chart v2.15.3
# Resources:
#  https://www.digitalocean.com/community/developer-how-to-encrypt-kubernetes-secrets-using-sealed-secrets-in-doks
#  https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers

# Make sure Ingress is disabled for security reasons
ingress:
  enabled: false

# kubeseal expectation. Otherwise run `kubeseal --controller-name sealed-secrets`
fullnameOverride: sealed-secrets-controller

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 500Mi