---
# adapted from techno-tim.
- name: Create metallb templates on Ansible Controller.
  run_once: true
  block:
    - name: Copy metallb kustomization.yaml template to gitops repo on ansible controller
      ansible.builtin.template:
        src: "kustomization.yaml.j2"
        dest: "{{ lookup('env', 'PWD') }}/infrastructure/metallb/base/kustomization.yaml"
        #owner: "{{ lookup('env', 'USER') }}"
        #group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      delegate_to: localhost
    - name: Copy metallb custom resource spec template to gitops repo on ansible controller
      ansible.builtin.template:
        src: "pool_advertisement.yaml.j2"
        dest: "{{ lookup('env', 'PWD') }}/infrastructure/metallb/base/pool_advertisement.yaml"
        #owner: "{{ lookup('env', 'USER') }}"
        #group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      delegate_to: localhost
